# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LBvd7d_SIx7oj_C0fNXNn-NcPmdbGNS4
"""

# Ushan Dilusha

import hashlib
msg = input("Enter Message :-")

hashFunc = hashlib.md5(msg.encode('utf-8'))
print('mesage with md5')
print(hashFunc.hexdigest())
