# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LBvd7d_SIx7oj_C0fNXNn-NcPmdbGNS4
"""

# Ushan Dilusha


# with sha256

msg = input("Enter Message :- ")
import hashlib
print('message with sha256')
shaFun = hashlib.sha256(msg.encode('utf-8'))
print(shaFun.hexdigest())



# with blake2b
print('message with blake2b')
blake2bFun = hashlib.blake2b(msg.encode('utf-8'))
print(blake2bFun.hexdigest())



# with shake_256
print('message with shake_256')
shake_256Fun = hashlib.shake_256(msg.encode('utf-8'))
print(shake_256Fun.hexdigest(32))
