# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LBvd7d_SIx7oj_C0fNXNn-NcPmdbGNS4
"""

# Ushan Dilusha

# add salt

import time
print('time stamp')
print(time.time())
import hashlib
timestamp = str(time.time())
salt = hashlib.md5(timestamp.encode('utf-8'))
print('Salt')
print(salt.hexdigest())
key = (salt.hexdigest())

message = 'join to our clan'
newPass = key + message
print('Salt + message ')
print(newPass)
hashFunc = hashlib.md5(newPass.encode('utf-8'))
print('############################################')
print('final message from md 5')
print(hashFunc.hexdigest())
finalmsg = (hashFunc.hexdigest())

print('############################################')

hashFunc = hashlib.sha256(newPass.encode('utf-8'))
print('final message from sha256')
print(hashFunc.hexdigest())
finalmsg = (hashFunc.hexdigest())

print('############################################')

hashFunc = hashlib.blake2b(newPass.encode('utf-8'))
print('final message from blake2b')
print(hashFunc.hexdigest())
finalmsg = (hashFunc.hexdigest())
print('############################################')
#add iterations

for x in range(6):
  hashFunc = hashlib.md5(finalmsg.encode('utf-8'))
  finalmsg = hashFunc.hexdigest()

print('final message from iterations & md5')
print(hashFunc.hexdigest())

print('############################################')

for x in range(6):
  hashFunc = hashlib.sha256(finalmsg.encode('utf-8'))
  finalmsg = hashFunc.hexdigest()

print('final message from iterations & sha256')
print(hashFunc.hexdigest())

print('############################################')

for x in range(6):
  hashFunc = hashlib.blake2b(finalmsg.encode('utf-8'))
  finalmsg = hashFunc.hexdigest()

print('final message from iterations & blake2b')
print(hashFunc.hexdigest())


